<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Commercant [
	<!ELEMENT Commercant (Marchand*)>
		<!ELEMENT Marchand (StockArrayList*)>
			<!ATTLIST Marchand nomMarchand  CDATA #REQUIRED>
			<!ELEMENT StockArrayList (Alimentaire*, Consommable*)*>
			<!ATTLIST StockArrayList nomStock CDATA #REQUIRED>
				<!ELEMENT Alimentaire EMPTY>
					<!ATTLIST Alimentaire nom  CDATA #REQUIRED>
					<!ATTLIST Alimentaire poids  CDATA #REQUIRED>
					<!ATTLIST Alimentaire prixUnitaire  CDATA #REQUIRED>
				<!ELEMENT Consommable EMPTY>
					<!ATTLIST Consommable nom  CDATA #REQUIRED>
					<!ATTLIST Consommable qte  CDATA #REQUIRED>
					<!ATTLIST Consommable prixUnitaire  CDATA #REQUIRED>
]>

<Commercant>
	<Marchand nomMarchand='Robert'>
		<StockArrayList nomStock='monStock'>
			<Alimentaire nom='banane' poids='12' prixUnitaire='0.99' />
			<Alimentaire nom='patate' poids='5' prixUnitaire='1.8' />
			<Consommable nom='casserole' qte='3' prixUnitaire='12' />
		</StockArrayList>
		<StockArrayList nomStock='monStockPrive'>
			<Alimentaire nom='A1' poids='12' prixUnitaire='0.99' />
			<Alimentaire nom='A2' poids='5' prixUnitaire='1.8' />
			<Consommable nom='C1' qte='3' prixUnitaire='12' />
		</StockArrayList>
		<StockArrayList nomStock='monStockFamille'>
			<Alimentaire nom='A3' poids='12' prixUnitaire='0.99' />
			<Alimentaire nom='A4' poids='5' prixUnitaire='1.8' />
			<Consommable nom='C2' qte='3' prixUnitaire='12' />
		</StockArrayList>
	</Marchand>
	<Marchand nomMarchand='Gilbert'>
		<StockArrayList nomStock='monStock'>
			<Alimentaire nom='banane' poids='12' prixUnitaire='0.99' />
			<Alimentaire nom='patate' poids='5' prixUnitaire='1.8' />
			<Consommable nom='casserole' qte='3' prixUnitaire='12' />
		</StockArrayList>
		<StockArrayList nomStock='monStockPrive'>
			<Alimentaire nom='A1' poids='12' prixUnitaire='0.99' />
			<Alimentaire nom='A2' poids='5' prixUnitaire='1.8' />
			<Consommable nom='C1' qte='3' prixUnitaire='12' />
		</StockArrayList>
		<StockArrayList nomStock='monStockFamille'>
			<Alimentaire nom='A3' poids='12' prixUnitaire='0.99' />
			<Alimentaire nom='A4' poids='5' prixUnitaire='1.8' />
			<Consommable nom='C2' qte='3' prixUnitaire='12' />
			<Consommable nom="" qte="" prixUnitaire="" />
			<Alimentaire nom="" poids="" prixUnitaire=""/>
		</StockArrayList>
	</Marchand>
</Commercant>